name: Release

on:
  push:
    branches:
      - main

jobs:
  install:
    steps:
      - uses: ./.github/workflows/install.yml
  lint:
    steps:
      - uses: ./.github/workflows/lint.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
