name: Review

on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/install.yml
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/lint.yml
