name: Review

on:
  pull_request:

jobs:
  checkout:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/install.yml
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/lint.yml
